project/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # grapelli admin urls
    (r'^grappelli/', include('grappelli.urls')),
    
    (r'^wvb/', include('home.urls')),
    (r'^alumno/', include('alumno.urls')),
    (r'^institucion/', include('institucion.urls')),
    (r'^curso/', include('curso.urls')),
    (r'^docente/', include('docente.urls')),
    (r'^campus/', include('campus.urls')),
    (r'^pago/', include('pago.urls')),
    (r'^boleta/', include('boleta.urls')),
    (r'^calificacion/', include('calificacion.urls')),
    (r'^print/', include('print.urls')),
)

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^favicon\.ico$', 
            'django.views.generic.simple.redirect_to', 
            {'url': '/static/images/favicon.ico'}),
    )

src/apps/campus/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('campus.views',
	url(r'^crear/$','campus', name='campus-registrar'),
	url(r'^listar/$','campus_listar', name='campus-listar'),
	url(r'^nuevo/listar/(?P<campus_id>\d+)/$','campus_new_listar', name='campus-nuevo-listar'),
	url(r'^registrar/$','campus', name='campus-registrar'),
	url(r'^matriculado/(?P<carrera_id>\d+)-(?P<ano>\d+)-(?P<turno>\d+)/json/$','campus_matriculado', name='campus-matriculado-json'),
	url(r'^matriculado/alumnos/(?P<campus_id>\d+)/json/$','campus_matriculado_alumno', name='campus-matriculado-alumno-json'),
	url(r'^registro-academico/$','registro_academico', name='campus-registro-academico'),
	url(r'^registrar/registro-academico/$','registro_academico', name='campus-registrar-registro-academico'),
	url(r'^registro-academico/(?P<ciclo_id>\d+)-(?P<ano>\d+)-(?P<seccion>\d+)-(?P<turno>\d+)-(?P<semestre>\d+)/ajax/$','registro_academico_ajax',name='campus-registro-academico'),
)

src/apps/campus/models.py
# -*- coding: utf-8 -*-
from django.db import models
from institucion.models import Ciclo
from alumno.models import Alumno
from concepto.models import Concepto

"""
App for Campus
"""

TURNO = (
    (0, 'Mañana'),
    (1, 'Tarde'),
    (2, 'Noche'),
)

SEMESTRE = (
    (0, 'I'),
    (1, 'II'),
)

SECCION = (
    ('Aula', (
            (0, 'A'),
            (1, 'B'),
            (2, 'C'),
            (3, 'D'),
            (4, 'E'),
            (5, 'F'),
            (6, 'G'),
        )
    ),
    ('Laboratorio', (
            (7, 'LAB. 1'),
            (8, 'LAB. 2'),
            (9, 'LAB. 3'),
        )
    ),
)

class Campus(models.Model):
    ciclo        = models.ForeignKey(Ciclo)
    seccion      = models.IntegerField('Sección', choices=SECCION)
    semestre     = models.IntegerField('Semestre', choices=SEMESTRE)
    fecha_inicio = models.DateField('Fecha de Inicio')
    fecha_fin    = models.DateField('Fecha de Fin')
    turno        = models.IntegerField('Turno', choices=TURNO)
    precio       = models.ForeignKey(Concepto)

    class Meta:
        verbose_name = "Campus"
        verbose_name_plural = "Campus"
        unique_together = (('ciclo', 'seccion','semestre','fecha_inicio','fecha_fin','turno','precio'),)

    def __unicode__(self):
        return u'%s - %s' % (self.get_turno(),self.get_seccion())

    def get_turno(self):
        t = ['Manana','Tarde','Noche']
        return u'%s' % t[self.turno]

    def get_seccion(self):
        t = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'LAB. 1', 'LAB. 2', 'LAB. 3',]
        return u'%s' % t[self.seccion]

class AlumnoCampus(models.Model):
    alumno     = models.ForeignKey(Alumno)
    campus     = models.ForeignKey(Campus)
    total      = models.DecimalField('Total', max_digits=8, decimal_places=1)
    deuda      = models.DecimalField('Deuda', max_digits=8, decimal_places=1)
    confirmado = models.BooleanField('¿Confirmado?', default = False)
    actual     = models.BooleanField('Actual', default = True)

    class Meta:
        unique_together = (('alumno', 'campus','total','deuda','confirmado','actual'),)

src/apps/curso/models.py
from django.db import models
from institucion.models import Ciclo
from docente.models import Docente
from campus.models import Campus

"""
App for Curso
"""

class Curso(models.Model):
    ciclo = models.ForeignKey(Ciclo)
    curso = models.CharField('Curso', max_length=30)

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"

    def __unicode__(self):
        return u'%s' % (self.curso)

class CursoDocente(models.Model):
    docente = models.ForeignKey(Docente)
    curso   = models.ForeignKey(Curso)
    campus  = models.ForeignKey(Campus)

src/apps/campus/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Campus, TURNO, SEMESTRE, SECCION
from institucion.models import Carrera
from operator import itemgetter
import datetime

"""
Simple ModelForm for Campus
"""
def get_years():
    years = [(year, year) for year in range(1965, datetime.date.today().year+1)]
    return sorted(years, key=itemgetter(0), reverse=True)

class CampusForm(forms.ModelForm):
    class Meta:
        model = Campus

class CampusSearchForm(forms.Form):
    search_years    = forms.IntegerField(widget=forms.Select(choices=get_years()))
    search_carrera  = forms.ModelMultipleChoiceField(queryset=Carrera.objects.all())
    search_semestre = forms.IntegerField(widget=forms.Select(choices=SEMESTRE))
    search_turno    = forms.IntegerField(widget=forms.Select(choices=TURNO))
    search_seccion  = forms.IntegerField(widget=forms.Select(choices=SECCION))

src/apps/campus/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import simplejson
from django.contrib.auth.decorators import login_required
from institucion.forms import CicloForm
from institucion.models import Carrera, Ciclo
from concepto.models import Concepto
from docente.models import Docente
from curso.models import Curso, CursoDocente
from alumno.models import Alumno
from models import Campus, AlumnoCampus
from calificacion.models import Nota
from boleta.forms import ConceptoForm
from forms import CampusForm, CampusSearchForm
from datetime import date, datetime
from django.db.models import Q

code = "000000"

@login_required(login_url='/wvb/')
def campus(request):
    if request.method == 'POST':
        fecha_inicio = datetime.strptime(str(request.POST["fecha_inicio"]),'%d/%m/%Y'),
        fecha_fin = datetime.strptime(str(request.POST["fecha_fin"]),'%d/%m/%Y'),
        ciclo = Ciclo.objects.get(pk = request.POST["ciclo"])
        concepto = ConceptoForm(request.POST)
        if concepto.is_valid():
            concepto.save()
        campus = Campus.objects.create(
                     ciclo = ciclo,
                     seccion = request.POST["seccion"],
                     semestre = 0 if (fecha_inicio[0].month <=6) else 1,
                     fecha_inicio = fecha_inicio[0],
                     fecha_fin = fecha_fin[0],
                     turno = request.POST["turno"],
                     precio = concepto.instance)
        campus.save()
        cursos = request.POST.getlist("cursos")
        matriculas = request.POST.getlist("matricular")
        decentes = request.POST.getlist("docente")
        for index in range(0, len(cursos)):
            curso_docente = CursoDocente.objects.create(
                                curso = Curso.objects.get(pk=cursos[index]),
                                docente = Docente.objects.get(pk=decentes[index]),
                                campus = campus)
            curso_docente.save()
        for matricula in matriculas:
            alumno = Alumno.objects.get(pk=matricula)
            if not alumno.matriculado:
                alumno.matriculado = True
                total_alumnos = (Alumno.objects.exclude(codigo="").count()+1)
                alumno.codigo = code[0:(len(code)-len(str(total_alumnos)))]+str(total_alumnos)
                alumno.save()
            AlumnoCampus(alumno = alumno,campus = campus,total = 0, deuda = campus.precio.precio*ciclo.carrera.duracion).save()
        return redirect('/campus/nuevo/listar/'+str(campus.pk)+'/')
    campus_form = CampusForm()
    campus_search_form = CampusSearchForm()
    ciclo_form = CicloForm()
    carrera = Carrera.objects.get(pk=1)
    ciclos = carrera.ciclo_set.all().order_by('pk')
    conceptoform = ConceptoForm()
    docentes = Docente.objects.filter(activo=True)
    alumnos_no_matriculados = Alumno.objects.filter(matriculado=False)
    return render(request,
                    'campus/campus.html',
                    { 'campus_form': campus_form, "campus_search_form" : campus_search_form, "ciclo_form":ciclo_form,"carrera":carrera,"docentes":docentes,"alumnos_no_matriculados":alumnos_no_matriculados,'ciclos':ciclos, 'conceptoform' : conceptoform})

@login_required(login_url='/wvb/')
def campus_listar(request):
    campus_search_form = CampusSearchForm()
    carrera = Carrera.objects.get(pk=1)
    ciclos = carrera.ciclo_set.all().order_by('pk')
    return render(request,
                    'campus/campus-listar.html',
                    { 'campus_search_form': campus_search_form,"ciclos":ciclos, })

@login_required(login_url='/wvb/')
def campus_new_listar(request, campus_id):
    campus_search_form = CampusSearchForm()
    campus = Campus.objects.get(pk = campus_id)
    campusalumno = AlumnoCampus.objects.filter(campus = campus)
    carrera = Carrera.objects.get(pk=1)
    ciclos = carrera.ciclo_set.all().order_by('pk')
    return render(request,
                    'campus/campus-listar.html',
                    {'campus_search_form' : campus_search_form, "ciclos" : ciclos, 'campusalumno' : campusalumno, })

@login_required(login_url='/wvb/')
def campus_matriculado(request, carrera_id, ano, turno):
    ciclos = Carrera.objects.get(pk=carrera_id).ciclo_set.all()
    campus_get = Campus.objects.filter(ciclo__in = ciclos, fecha_inicio__year = ano,turno = turno)
    json_array = [{ "ciclo" : campus.ciclo.ciclo , "seccion" : campus.seccion, "id" : campus.pk  } for campus in campus_get]
    return HttpResponse(simplejson.dumps(json_array),mimetype='application/json')

@login_required(login_url='/wvb/')
def campus_matriculado_alumno(request, campus_id):
    campus = Campus.objects.get(pk = campus_id)
    campus_alumno_get = AlumnosCampus.objects.filter(campus = campus)
    json_array = [{ "id" : campus.alumno.pk , "dni" : campus.alumno.dni, "nombre" : campus.alumno.nombre, "apellido" : campus.alumno.apellido } for campus in campus_alumno_get]
    return HttpResponse(simplejson.dumps(json_array),mimetype='application/json')

@login_required(login_url='/wvb/')
def registro_academico(request):
    if request.method == 'POST':
        alumnos = request.POST.getlist("alumnos")
        notas = request.POST.getlist("notas")
        campus = Campus.objects.get(pk = request.POST["campus"])
        cursodocente = CursoDocente.objects.get(pk = request.POST["cursos_docente"])
        for index,alumno in enumerate(alumnos):
            Nota.objects.create(
                alumno_campus = AlumnoCampus.objects.get(Q(alumno = Alumno.objects.get(pk = alumno)) , Q(campus = campus)),
                curso_docente = cursodocente,
                nota = notas[index]).save()
        return redirect('/campus/registro-academico/')
    carrera = Carrera.objects.get(pk=1)
    campus_search_form = CampusSearchForm()
    carrera = Carrera.objects.get(pk=1)
    ciclos = carrera.ciclo_set.all().order_by('pk')
    return render(request, 'campus/registro_academico.html', { 'campus_search_form': campus_search_form,'ciclos':ciclos },)

@login_required(login_url='/wvb/')
def registro_academico_ajax(request,ciclo_id,ano,seccion,turno,semestre):
    try:
        campus = Campus.objects.get(
                    fecha_inicio__year = ano,
                    seccion = seccion,
                    semestre = semestre,
                    turno = turno,
                    ciclo = Ciclo.objects.get(pk=ciclo_id))
        alumnos = campus.alumnocampus_set.all()
        docentes = CursoDocente.objects.filter(~Q(pk__in = Nota.objects.values('curso_docente').filter(alumno_campus__in = alumnos).distinct()), Q(campus = campus))
    except:
        return render(request, 'campus/registro_academico_ajax.html')
    return render(request, 'campus/registro_academico_ajax.html', { 'alumnos': alumnos,'docentes':docentes,"campus":campus,})

templates/campus/campus-listar.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Campus{% endblock %}
{% block csspage %}
	<link href="{{ STATIC_URL  }}css/jquery.treeTable.css" rel="stylesheet" type="text/css" />
	<style>
		#toolbar {
			padding: 10px 4px;
		}
	</style>
{% endblock %}
{% block content %}
	<form method="post" action="#" class="yform full" role="application">
		{% csrf_token %}
		{% if not campusalumno %}
			<fieldset>
				<legend>Campus</legend>
				<div class="subcolumns">
					<div class="c50l">
						<div class="subcl type-select">
							<label for="id_search_carrera">Carrera:</label>
							{{ campus_search_form.search_carrera }}
						</div>
						<div class="subcl type-select">
							{% if ciclos|length > 0 %}
								<label for="id_ciclo">Ciclo:</label>
								<select id="id_ciclo" name="ciclo">
									{% for ciclo in ciclos %}
									<option value="{{ ciclo.id }}">{{ ciclo.ciclo }}</option>
									{% endfor %}
								</select>
							{% else %}
								<p>No hay ciclos disponibles.</p>
							{% endif %}
						</div>
					</div>
					<div class="c50r">
						<div class="subcl type-select">
							<label for="id_search_years">Año:</label>
							{{ campus_search_form.search_years }}
						</div>
						<div class="subcl type-select">
							<label for="id_search_turno">Turno:</label>
							{{ campus_search_form.search_turno }}
						</div>
						<div class="subcr type-select">
							<label for="id_search_semestre">Semestre:</label>
							{{ campus_search_form.search_semestre }}
						</div>
					</div>
				</div>
			</fieldset>
			<div class="type-button">
				<input type="button" value="Buscar Campus" class="button" id="search_campus" name="search_campus" />
			</div>
		{% endif %}
		<fieldset>
			<table id="talumnos">
				<thead>
					<th colspan="3">
						<div>
						<span id="toolbar" class="ui-widget-header ui-corner-all">
							<button type="button" id="lista-asistencia">Imprimir Lista de Asistencia</button>
						</span>
						</div>
					</th>
				</thead>
				<tbody>
					{% if campusalumno %}
						<tr id='node-1'>
							<td>{{ campusalumno.0.campus.ciclo.carrera }}</td>
							<td>{{ campusalumno.0.campus.ciclo.ciclo }} - {{ campusalumno.0.campus.get_seccion }}</td>
							<td>{{ campusalumno.0.campus.get_turno }}</td>
							
						</tr>
						{% for campus_alumno in campusalumno %}
							<tr class="child-of-node-1">
								<td>{{ campus_alumno.alumno.dni }}</td>
								<td>{{ campus_alumno.alumno.nombre }}</td>
								<td>{{ campus_alumno.alumno.apellido }}</td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>
			<input type='hidden' id='campus_id' {% if campusalumno %} value='{{ campusalumno.0.campus.id }}' {% endif %}/>
		</fieldset>
	</form>
{% endblock %}
{% block left-bar %}
    {% include 'home/academico.html' %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL  }}js/base.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.selectboxes.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.treeTable.js" type="text/javascript"></script>
	<script>
		var ciclos = null;
		var talumnos = null;
		$(document).ready(function() {
			run();
			ciclos = $("#id_ciclo");
			talumnos = $("#talumnos").treeTable();
			$("#search_campus").button({
				text:true,
				icons:{
					primary: "ui-icon-check"
				}
			}).click(function(){
				getAlumnosMatriculados();
			});
			$("#id_turno option[value=1]").attr("selected",true);
			$("#id_carrera option[value=1]").attr("selected",true);
			$("#id_carrera").change(function() {
				ciclos.removeOption(/./);
				$.getJSON("/institucion/ciclos/"+this.value+"/json/", function(data){
					var val = null;
					$.each(data, function(key, value){
						if(key==0){
							val = value.pk;
						}
						ciclos.addOption(value.pk, value.fields.ciclo);
					});
					ciclos.find('option').first().attr('selected',true);
				});
			});
			$( "#lista-asistencia" ).button({
				text: false,
				icons: {
					primary: "ui-icon-note"
				}
				}).click(function(){
					window.location.href='/print/lista/asistencia/'+$("#campus_id").val()+'/';
			});
		});
		function getAlumnosMatriculados(){
			seccion = $("#id_seccion").val();
			fecha_incio = $("#id_fecha_inicio").val().replace(/[/]/g,"");
			semestre = $("#semestreI").checked ? $("#semestreI").val() : $("#semestreII").val();
		}
	</script>
{% endblock %}

templates/campus/registro_academico.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Registro Académico{% endblock %}
{% block csspage %}
	<style>
		#id_alumno{
			width: 97.8%;
		}
		#toolbar {
			padding: 10px 4px;
		}
	</style>
{% endblock %}
{% block content %}
	<form method="post" action="/campus/registrar/registro-academico/" class="yform full" role="application" onSubmit="return confirmar('¿Esta segur@ que desea registrar?');">
		{% csrf_token %}
		<div class="subcolumns">
			<fieldset>
				<legend>Campus</legend>
				<div class="c50l">
					<div class="subcl">
						<div class="subcl type-select">
							{{ campus_search_form.search_carrera.errors }}
							<label for="id_carrera">Carrera:</label>
							{{ campus_search_form.search_carrera }}
						</div>
						<div class="subcl type-select">
							{% if ciclos|length > 0 %}
								<label for="id_ciclo">Ciclo:</label>
								<select id="id_ciclo" name="ciclo">
								{% for ciclo in ciclos %}
									<option value="{{ ciclo.id }}">{{ ciclo.ciclo }}</option>
								{% endfor %}
								</select>
							{% else %}
								<p>No hay ciclos disponibles.</p>
							{% endif %}
						</div>
						<div class="subcl type-select">
							{{ campus_search_form.search_years.errors }}
							<label for="id_search_years">Año:</label>
							{{ campus_search_form.search_years }}
						</div>
					</div>
				</div>
				<div class="c50r">
					<div class="subcr">
						<div class="subcl type-select">
							{{ campus_search_form.search_seccion.errors }}
							<label for="id_seccion">Sección:</label>
							{{ campus_search_form.search_seccion }}
						</div>
						<div class="subcl type-select">
							{{ campus_search_form.search_turno.errors }}
							<label for="id_turno">Turno:</label>
							{{ campus_search_form.search_turno }}
						</div>
						<div class="subcl type-select">
							{{ campus_search_form.search_semestre.errors }}
							<label for="id_semestre">Semestre:</label>
							{{ campus_search_form.search_semestre }}
						</div>
						<div class="type-button">
							<input type="button" value="Buscar" class="button" id="buscar" name="buscar" onclick='getAlumnosMatriculados();'/>
							<input type="submit" value="Registrar" class="submit" id="submit" name="submit" />
						</div>
					</div>
				</div>
			</fieldset>
		</div>
		<fieldset>
			<legend>Alumnos</legend>
			<table id="talumnos"></table>
		</fieldset>
	</form>
{% endblock %}
{% block left-bar %}
    {% include "home/academico.html" %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL  }}js/base.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.selectboxes.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.tablesorter.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.uitablefilter.js" type="text/javascript"></script>
	<script>
		var ciclos = null;
		var talumnos = null;
		$(document).ready(function() {
			run();
			ciclos = $("#id_ciclo");
			$("#id_turno option[value=1]").attr("selected",true);
			$("#id_search_carrera option[value=1]").attr("selected",true);
			$("#id_search_carrera").change(function() {
				ciclos.removeOption(/./);
				$.getJSON("/institucion/ciclos/"+this.value+"/json/", function(data){
					var val = null;
					$.each(data, function(key, value){
						if(key==0){
							val = value.pk;
						}
						ciclos.addOption(value.pk, value.fields.ciclo);
					});
					ciclos.find('option').first().attr('selected',true);
				});
			});
			talumnos = $("#talumnos").tablesorter();
			tbalumnos = $("#talumnos");
			$("#filtra_alumno").keyup(function() {
				$.uiTableFilter( tbalumnos, this.value );
			});
		});
		function getAlumnosMatriculados(){
			var seccion = $("#id_search_seccion").val();
			var ano = $("#id_search_years").val();
			var semestre = $("#id_search_semestre").val();
			var turno = $("#id_search_turno").val();
			tbalumnos.html($.ajax({
					url: "/campus/registro-academico/"+ciclos.val()+"-"+ano+"-"+seccion+"-"+turno+"-"+semestre+"/ajax/",
					dataType: "html",
					async: false
				}).responseText);
		}
	</script>
{% endblock %}

templates/campus/registro_academico_ajax.html
{% if campus %}
	<thead>
	<tr>
		<th>
			Alumno | Curso
			<input type="hidden" name="campus" id="campus" value="{{ campus.id }}"/>
		</th>
		<th>
			<div class="subcl type-select">
				<select id="cursos_docente" name="cursos_docente">
					{% for docente in docentes %}
						<option value="{{ docente.id }}">{{ docente.curso.curso }}</option>
					{% endfor %}
				</select>
			</div>
		</th>
	</tr>
	</thead>
	<tbody>
	{% for alumno in alumnos %}
	<tr>
		<th>
			<input type="hidden" name="alumnos" id="{{ alumno.alumno.id }}" value="{{ alumno.alumno.id }}"/>
			{{ alumno.alumno.nombre }} {{ alumno.alumno.apellido }}
		</th>
		<td><input type="text" name="notas" id="{{ docente.id }}" value="0" maxlength=2 /></td>
	</tr>
	{% endfor %}}
	</tbody>
	<tfoot>
		<tr>
			<td>Total de Alumnos</td><td>{{ alumnos|length }}</td>
		</tr>
	</tfoot>
{% else %}
	<thead>
		<tr>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>No hay un Campus</td>
		</tr>
	</tbody>
{% endif %}