project/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # grapelli admin urls
    (r'^grappelli/', include('grappelli.urls')),
    
    (r'^wvb/', include('home.urls')),
    (r'^alumno/', include('alumno.urls')),
    (r'^institucion/', include('institucion.urls')),
    (r'^curso/', include('curso.urls')),
    (r'^docente/', include('docente.urls')),
    (r'^campus/', include('campus.urls')),
    (r'^pago/', include('pago.urls')),
    (r'^boleta/', include('boleta.urls')),
    (r'^calificacion/', include('calificacion.urls')),
    (r'^print/', include('print.urls')),
)

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^favicon\.ico$', 
            'django.views.generic.simple.redirect_to', 
            {'url': '/static/images/favicon.ico'}),
    )

src/apps/alumno/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('alumno.views',
    url(r'^guardar/$', 'alumno', name='alumno-listar'),
    url(r'^registrar/$','alumno', name='alumno-registrar'),
    url(r'^historial/$','alumno_historial', name='alumno-historial'),
    url(r'^historial/(?P<alumno>\d+)-(?P<tipo>\d+)/ajax/$','alumno_historial_ajax', name='alumno-historial-ajax'),
)

src/apps/alumno/models.py
# -*- coding: utf-8 -*-
from django.db import models

"""
App for Alumno
"""
SEXO = (
        ('F','Femenino'),
        ('M','Masculino'),
        )

class Alumno(models.Model):
    codigo           = models.CharField('Código', max_length=10, blank=True, null=True)
    numero_matricula = models.CharField('Número Matricula', max_length=12, blank=True, null=True)
    apellido         = models.CharField('Apellido', max_length=200)
    nombre           = models.CharField('Nombre', max_length=200)
    dni              = models.CharField('D.N.I.', max_length=12, unique=True)
    telefono         = models.CharField('Teléfono', max_length=10, blank=True, null=True)
    sexo             = models.CharField('Sexo', max_length=1, choices = SEXO, blank=True, null=True)
    celular          = models.CharField('Celular', max_length=12, blank=True, null=True)
    fecha_nacimiento = models.DateField('Fecha de Nacimiento', )
    direccion        = models.TextField('Dirección', blank=True, null=True)
    foto             = models.ImageField('Foto', upload_to='alumno/', blank=True, null=True)
    apoderado        = models.CharField('Apoderado', max_length=250)
    email            = models.EmailField('E-Mail')
    matriculado      = models.BooleanField('Matriculado', default=False)

    class Meta:
        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'
        unique_together = (('apellido', 'nombre','codigo','dni','numero_matricula'),)

    def __unicode__(self):
        return self.get_full_name()

    def get_full_name(self):
		return u'%s,  %s' % (self.apellido, self.nombre)

src/apps/alumno/forms.py
from django import forms
from models import Alumno

"""
Simple ModelForm for Alumno
"""

class AlumnoForm(forms.ModelForm):
    class Meta:
        model = Alumno

src/apps/alumno/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from forms import AlumnoForm

@login_required(login_url='/wvb/')
def alumno(request):
    if request.method == 'POST':
        alumno_form = AlumnoForm(request.POST, request.FILES)
        if alumno_form.is_valid():
            alumno_form.save()
            return redirect('/alumno/registrar/')
    alumno_form = AlumnoForm()
    return render(request,
                    'alumno/alumno.html', 
                    { 'alumno_form': alumno_form })

@login_required(login_url='/wvb/')
def alumno_historial(request):
    return render(request,
                    'alumno/alumno_historial.html', {})

@login_required(login_url='/wvb/')
def alumno_historial_ajax(request,alumno,tipo):
    alu = Alumno.objects.get(pk=alumno)
    if int(tipo) == 1:
        alucampus = AlumnoCampus.objects.filter(alumno = alu)
        return render(request, 'alumno/alumno_historial_ajax.html', {'alucampus': alucampus,'academico':True})

templates/alumno/alumno.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Alumno{% endblock %}
{% block content %}
    <form method="post" action="/alumno/guardar/" class="yform full" role="application" enctype="multipart/form-data" onSubmit="return confirmar('¿Esta segur@ que desea registrar al alumno?');">
		{% csrf_token %}
		<fieldset>
			<legend>Matricula</legend>
			<div class="subcolumns">
				<div class="c50l">
					<div class="subcl type-text">
						{{ alumno_form.numero_matricula.errors }}
						<label for="id_dni">N° de Matricula:</label>
						{{ alumno_form.numero_matricula }}
					</div>
					<div class="subcl type-select">
						<label for="id_nombre">Carrera:</label>
						<select id='id_carrera' name='carrera'>
							{% for carrera in  carreras %}
							<option value='{{ carrera.id }}'>{{ carrera.carrera }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="c50r">
					<div class="subcl type-text">
						<label for="id_dni">Serie - Número:</label>
						<input id='id_serie_numero' name='serie_numero' value='{{ serie_numero.serie }} - {{ serie_numero.numero }}'/>
					</div>
					<div class="subcl type-select">
						<label for="id_nombre">Concepto:</label>
						<select id='id_concepto' name='concepto'>
							{% for concepto in  conceptos %}
							<option value='{{ concepto.id }}'>{{ concepto.concepto }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
			</div>
		</fieldset>
		<fieldset>
			<legend>Alumno</legend>
			<div class="subcolumns">
				<div class="c50l">
					<div class="subcl type-text">
						{{ alumno_form.dni.errors }}
						<label for="id_dni">D.N.I.:</label>
						{{ alumno_form.dni }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.nombre.errors }}
						<label for="id_nombre">Nombre:</label>
						{{ alumno_form.nombre }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.apellido.errors }}
						<label for="id_apellido">Apellido:</label>
						{{ alumno_form.apellido }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.fecha_nacimiento.errors }}
						<label for="id_fecha_nacimiento">Fecha Nacimiento:</label>
						{{ alumno_form.fecha_nacimiento }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.celular.errors }}
						<label for="id_celular">Celular:</label>
						{{ alumno_form.celular }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.foto.errors }}
						<label for="id_foto">Foto:</label>
						{{ alumno_form.foto }}
					</div>
				</div>
				<div class="c50r">
					<div class="subcl type-text">
						{{ alumno_form.apoderado.errors }}
						<label for="id_carrera">Apoderado:</label>
						{{ alumno_form.apoderado }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.email.errors }}
						<label for="id_email">E-mail:</label>
						{{ alumno_form.email }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.telefono.errors }}
						<label for="id_telefono">Teléfono:</label>
						{{ alumno_form.telefono }}
					</div>
					<div class="subcl type-select">
						{{ alumno_form.sexo.errors }}
						<label for="id_sexo">Sexo:</label>
						{{ alumno_form.sexo }}
					</div>
					<div class="subcl type-text">
						{{ alumno_form.direccion.errors }}
						<label for="id_carrera">Dirección:</label>
						{{ alumno_form.direccion }}
					</div>
			  </div>
			</div>
		</fieldset>
		<div class="type-button">
			  <input type="reset" value="Nuevo" class="reset" id="reset" name="reset" />
			  <input type="submit" value="Guardar" class="submit" id="submit" name="submit" />
		</div>
    </form>
{% endblock %}
{% block left-bar %}
    {% include 'home/academico.html' %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL  }}js/base.js" type="text/javascript"></script>
	<script>
		$(document).ready(function() {
			run();
			$("#id_fecha_nacimiento").datepicker({
						  changeMonth: true,
						  changeYear: true,
						  closeText: 'X',
						  dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
						  gotoCurrent: true,
						  monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
						  yearRange: '1950:'+new Date().getFullYear(),
						  dateFormat: 'dd/mm/yy',
						  currentText: 'Now'});
			$("#id_direccion").attr("rows","4");
			$("#id_dni").focus();
		});
	</script>
{% endblock %}