project/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # grapelli admin urls
    (r'^grappelli/', include('grappelli.urls')),
    
    (r'^wvb/', include('home.urls')),
    (r'^alumno/', include('alumno.urls')),
    (r'^institucion/', include('institucion.urls')),
    (r'^curso/', include('curso.urls')),
    (r'^docente/', include('docente.urls')),
    (r'^campus/', include('campus.urls')),
    (r'^pago/', include('pago.urls')),
    (r'^boleta/', include('boleta.urls')),
    (r'^calificacion/', include('calificacion.urls')),
    (r'^print/', include('print.urls')),
)

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^favicon\.ico$', 
            'django.views.generic.simple.redirect_to', 
            {'url': '/static/images/favicon.ico'}),
    )

src/apps/docente/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('docente.views',
	url(r'^listar/$','docente', name='docente-listar'),
	url(r'^registrar/$','docente', name='docente-registar'),
	url(r'^(?P<docente_id>\d+)/json/$','docente_json', name='docente-json'),
)

src/apps/docente/models.py
# -*- coding: utf-8 -*-
from django.db import models

"""
App for Docente
"""

class Docente(models.Model):
    nombre     = models.CharField('Nombre', max_length=150)
    apellido   = models.CharField('Apellido', max_length=150)
    dni        = models.CharField('D.N.I.', max_length=8, unique=True)
    fijo       = models.CharField('Fijo', max_length=10,blank=True,null=True)
    celular    = models.CharField('Celular', max_length=12,blank=True,null=True)
    direccion  = models.TextField('Dirección', blank=True,null=True)
    email      = models.EmailField('E-mail', blank=True, null=True)
    activo     = models.BooleanField('Activo', default=False)
    curriculum = models.FileField('Curriculum', upload_to='curriculum',blank=True,null=True)

    class Meta:
        verbose_name = "Docente"
        verbose_name_plural = "Docentes"
        unique_together = (('apellido', 'nombre'),)

    def __unicode__(self):
        return u'%s, %s' % (self.apellido,self.nombre)

src/apps/docente/forms.py
from django import forms
from models import Docente

"""
Simple Modelform for Docente
"""
class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente

src/apps/docente/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core import serializers
from forms import DocenteForm
from models import Docente

@login_required(login_url='/wvb/')
def docente(request):
    docente_form = DocenteForm()
    if request.method == 'POST':
        docente_form = DocenteForm(request.POST,request.FILES)
        if docente_form.is_valid():
            docente_form.save()
            return redirect('/docente/listar/')
    docentes_activos = Docente.objects.filter(activo=True).order_by('dni')
    docentes_inactivos = Docente.objects.filter(activo=False).order_by('dni')
    return render(request,
        'docente/docente.html',
        {'docente_form': docente_form, "docentes_activos":docentes_activos, "docentes_inactivos":docentes_inactivos},)

@login_required(login_url='/wvb/')
def docente_json(request,docente_id):
    json_d = Docente.objects.filter(pk=docente_id)
    json_serializer = serializers.get_serializer("json")()
    resultado = json_serializer.serialize(json_d, ensure_ascii=False)
    return HttpResponse(resultado,mimetype='application/json')

templates/docente/docente.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Docente{% endblock %}
{% block content %}
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Docentes</a></li>
			<li><a href="#tabs-2">Docente</a></li>
			<li><a href="#tabs-3">Inactivos</a></li>
		</ul>
		<form method="post" action="/docente/registrar/" class="yform full" role="application" enctype="multipart/form-data">
			{% csrf_token %}
			<div id="tabs-1">
				<fieldset>
					<legend>Docente</legend>
					{% if docentes_activos %}
						<table id="tdocente">
							<thead>
								<tr>
									<th>D.N.I.</th><th>Apellidos</th><th>Nombres</th><th>Celular</th><th>Curriculum</th>
								</tr>
							</thead>
							<tbody>
								{% for docente in docentes_activos %}
								<tr>
									<td><a href="#" onclick="getDocente({{ docente.id }});">{{ docente.dni }}</a></td>
									<td>{{ docente.apellido }}</td><td>{{ docente.nombre }}</td>
									<td>{{ docente.celular }}</td>
									<td>
										<a href="/media/{{ docente.curriculum }}"><img alt="curriculum del docente" src="{{ STATIC_URL  }}images/curriculum.png"/></a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
							<tfoot>
								<tr>
									<th>Número de docentes:</th>
									<th colspan="3">{{ docentes_activos|length }}</th>
								</tr>
							</tfoot>
						</table>
					{% else %}
						<p>No hay docentes registrados.</p>
					{% endif %}
				</fieldset>
			</div>
			<div id="tabs-2">
				<fieldset>
					<legend>Carrera</legend>
					<div class="subcolumns">
						<div class="c50l">
							<div class="subcl type-text">
							{{ docente_form.dni.errors }}
							<label for="id_dni">DNI:</label>
							{{ docente_form.dni }}
							</div>
							<div class="subcl type-text">
							{{ docente_form.nombre.errors }}
							<label for="id_nombre">Nombre:</label>
							{{ docente_form.nombre }}
							</div>
							<div class="subcl type-text">
							{{ docente_form.apellido.errors }}
							<label for="id_apellido">Apellido:</label>
							{{ docente_form.apellido }}
							</div>
							<div class="subcl type-text">
								{{ docente_form.email.errors }}
								<label for="id_email">E-mail:</label>
								{{ docente_form.email }}
							</div>
							<div class="subcl type-text">
							{{ docente_form.celular.errors }}
							<label for="id_celular">Celular:</label>
							{{ docente_form.celular }}
							</div>
						</div>
						<div class="c50r">
							<div class="subcr type-text">
								{{ docente_form.fijo.errors }}
								<label for="id_fijo">Fijo</label>
								{{ docente_form.fijo }}
							</div>
							<div class="subcl type-text">
								{{ docente_form.direccion.errors }}
								<label for="id_direccion">Direccion</label>
								{{ docente_form.direccion }}
							</div>
							<div class="subcr type-check">
								<div>
									{{ docente_form.activo.errors }}
									<label for="id_activo">Activo</label>
									{{ docente_form.activo }}
								</div>
							</div>
							<div class="subcl type-text">
								{{ docente_form.curriculum.errors }}
								<label for="id_curriculum">Curriculum</label>
								{{ docente_form.curriculum }}
							</div>
						</div>
					</div>
				</fieldset>
				<div class="type-button">
					<input type="reset" value="Nuevo" class="reset" id="reset" name="reset" />
					<input type="submit" value="Guardar" class="submit" id="submit" name="submit" />
				</div>
			</div>
			<div id="tabs-3">
				<fieldset>
					<legend>Docente Inactivos</legend>
					{% if docentes_inactivos %}
					<table>
						<tr>
							<th>D.N.I.</th><th>Apellidos</th><th>Nombres</th><th>Celular</th><th>Curriculum</th>
						</tr>
						{% for docente in docentes_inactivos %}
						<tr>
							<td><a href="#">{{ docente.dni }}</a></td>
							<td>{{ docente.apellido }}</td><td>{{ docente.nombre }}</td>
							<td>{{ docente.celular }}</td>
							<td>{{ docente.curriculum }}</td>
						</tr>
						{% endfor %}
					</table>
					{% else %}
						<p>No hay docentes inactivos registrados.</p>
					{% endif %}
				</fieldset>
			</div>
		</form>
	</div>
{% endblock %}
{% block left-bar %}
    {% include 'home/academico.html' %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL  }}js/base.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL  }}js/jquery.tablesorter.js" type="text/javascript"></script>
	<script>
		var tabs = null;
		$(document).ready(function() {
			run();
			$("#tabs").tabs();
			$("#id_direccion").attr("rows","5");
			$("#tdocente").tablesorter();
			tabs = $("#tabs").tabs();
		});
		function getDocente(iddocente){
			$.getJSON("/docente/"+iddocente+"/json/",function(data){
				$.each(data,function(key, value){
					$("#id_dni").val(value.fields.dni);
					$("#id_nombre").val(value.fields.nombre);
					$("#id_apellido").val(value.fields.apellido);
					$("#id_celular").val(value.fields.celular);
					$("#id_fijo").val(value.fields.fijo);
					$("#id_direccion").val(value.fields.direccion);
					$("#id_activo").attr("checked",value.fields.activo)
				 });
			 });
		    tabs.tabs('select', 1);
		}
	</script>
{% endblock %}