project/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # grapelli admin urls
    (r'^grappelli/', include('grappelli.urls')),
    
    (r'^wvb/', include('home.urls')),
    (r'^alumno/', include('alumno.urls')),
    (r'^institucion/', include('institucion.urls')),
    (r'^curso/', include('curso.urls')),
    (r'^docente/', include('docente.urls')),
    (r'^campus/', include('campus.urls')),
    (r'^pago/', include('pago.urls')),
    (r'^boleta/', include('boleta.urls')),
    (r'^calificacion/', include('calificacion.urls')),
    (r'^print/', include('print.urls')),
)

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^favicon\.ico$', 
            'django.views.generic.simple.redirect_to', 
            {'url': '/static/images/favicon.ico'}),
    )

src/apps/boleta/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('boleta.views',
	url(r'^boleta-campus/(?P<codigo_alumno>\w+)/json/$','alumno_boleta_json', name='alumno-boleta-json'),
	url(r'^boleta-alumno-campus/json/','alumno_boleta_nombre_json', name='alumno-boleta-nombre-json'),
	url(r'^(?P<boleta_id>\d+)/imprimir/$','boleta_imprimir',name='boleta-imprimir'),
	url(r'^(?P<serie>\w+)/(?P<numero>\w+)/json/$', 'boleta_json',name='boleta-json'),
	url(r'^historial/$', 'boleta_historial',name='boleta-historial'),
	url(r'^boleta-alumno-campus-id/json/','alumno_boleta_id_json', name='alumno-boleta-id-json'),
	url(r'^buscar/(?P<serie>\w+)/(?P<numero>\w+)/(?P<alumno>\w+)/(?P<fecha_inicio>\w+)/(?P<fecha_fin>\w+)/(?P<anulado>\w+)/json/','boleta_buscar', name='boleta-buscar'),
)

src/apps/boleta/models.py
# -*- coding: utf-8 -*-
from django.db import models
from campus.models import AlumnoCampus
from concepto.models import Concepto

class Boleta(models.Model):
    alumno        = models.ForeignKey(AlumnoCampus)
    serie         = models.CharField('Serie', max_length=3)
    numero        = models.CharField('Número', max_length=7)
    concepto      = models.ForeignKey(Concepto)
    fecha_emision = models.DateTimeField('Fecha de emisión')
    valido        = models.BooleanField('¿Valida?', default=True)
    importe       = models.DecimalField('Importe', max_digits=8,decimal_places=1)
    saldo         = models.DecimalField('saldo', max_digits=8,decimal_places=1)
    observacion   = models.TextField('Observación', blank=True,null=True)

    class Meta:
        verbose_name = 'Boleta'
        verbose_name_plural = 'Boletas'
        unique_together = (('serie', 'numero'),)

    def __unicode__(self):
        return u'%s - %s' % (self.serie,self.numero)

    def get_url_imprimir(self):
        return u'/%s/%s/%s' % ('boleta',self.id,'imprimir')

src/apps/boleta/forms.py
from django import forms
from models import Boleta, Concepto

class BoletaForm(forms.ModelForm):
    class Meta:
        model = Boleta

class ConceptoForm(forms.ModelForm):
    class Meta:
        model = Concepto

src/apps/boleta/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import simplejson
from django.core import serializers
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.db import connection
from models import Boleta
from alumno.models import Alumno
from campus.models import Campus, AlumnoCampus
import datetime

numero_boleta = "0000000"
serie_boleta = "000"

def get_serie_numero():
    numero_serie = Boleta.objects.values("serie","numero").order_by("-serie","-numero")
    if len(numero_serie)==0:
        numero_serie = {'serie':'001','numero':'0000001',}
    else:
        numero_serie = numero_serie[0]
        if(int(numero_serie["numero"]==9999999)):
            numero_serie["numero"] = "0000001"
            nueva_serie = str(int(numero_serie["serie"])+1)
            numero_serie["serie"] = serie_boleta[3:-len(int(nueva_serie))]+nueva_serie
        else:
            nuevo_numero = str(int(numero_serie["numero"])+1)
            numero_serie["numero"] = numero_boleta[0:7-len(nuevo_numero)]+nuevo_numero
    return numero_serie

@login_required(login_url='/wvb/')
def alumno_boleta_json(request,codigo_alumno):
    alumno = Alumno.objects.get(codigo = codigo_alumno)
    alumnocampus = AlumnoCampus.objects.get(Q(actual = True), Q(alumno = alumno))
    boleta_json = {
                      "codigo" : alumno.codigo,
                      "alumno" : u'%s %s' % (alumno.apellido, alumno.nombre),
                      "turno" : alumnocampus.campus.get_turno().encode("ascii","ignore"),
                      "ciclo_seccion" : u'%s - %s' % (alumnocampus.campus.ciclo.ciclo, alumnocampus.campus.get_seccion()),
                      "carrera" : alumnocampus.campus.ciclo.carrera.carrera,
                      "precio_pension" : str(alumnocampus.campus.precio.precio),
                      }
    return HttpResponse(simplejson.dumps(boleta_json),mimetype='application/json')

@login_required(login_url='/wvb/')
def alumno_boleta_nombre_json(request):
    alumno = request.GET.get('term')
    alumnos = Alumno.objects.values('codigo', 'nombre', 'apellido').filter(Q(nombre__icontains = alumno) | Q(apellido__icontains = alumno), Q(matriculado = True))
    resultado = [{'id' : alumnoselect['codigo'], 'value' : u'%s, %s' % (alumnoselect['apellido'], alumnoselect['nombre'])} for alumnoselect in alumnos]
    return HttpResponse(simplejson.dumps(resultado),mimetype='application/json')

@login_required(login_url='/wvb/')
def alumno_boleta_id_json(request):
    alumno = request.GET.get('term')
    alumnos = Alumno.objects.values('id', 'nombre', 'apellido').filter(Q(nombre__icontains = alumno) | Q(apellido__icontains = alumno), Q(matriculado = True))
    resultado = [{'id' : alumnoselect['id'], 'value' : u'%s, %s' % (alumnoselect['apellido'], alumnoselect['nombre'])} for alumnoselect in alumnos]
    return HttpResponse(simplejson.dumps(resultado),mimetype='application/json')

@login_required(login_url='/wvb/')
def boleta_imprimir(request, boleta_id):
    boleta = Boleta.objects.get(pk = boleta_id)
    return render(request, 'boleta/boleta_imprimir.html', {'boleta' : boleta,})

@login_required(login_url='/wvb/')
def boleta_historial(request):
    date_ini = datetime.datetime.today().replace(minute=0,hour=0)
    boletas = Boleta.objects.filter(fecha_emision__range=(date_ini,datetime.datetime.today())).order_by("-fecha_emision")
    return render(request, "boleta/boleta_historial.html",{ 'boletas':boletas, },)

@login_required(login_url='/wvb/')
def boleta_json(request, serie, numero):
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM public.boleta_alumno WHERE serie = '%s' AND numero = '%s'" % (serie, numero))
    boleta = cursor.fetchone()
    boleta_json = {
				  "valido" : boleta[0],
				  "serie" : boleta[1],
				  "saldo" : str(boleta[2]),
				  "numero" : boleta[3],
				  "fecha" : str(boleta[4]),
				  "importe" : str(boleta[5]),
				  "concepto" : boleta[6],
				  "alumno" : u'%s, %s' % (boleta[7],boleta[8]),
				  "codigo" : boleta[9],
				  }
    return HttpResponse(simplejson.dumps(boleta_json), mimetype='application/json')

@login_required(login_url='/wvb/')
def boleta_buscar(request, serie, numero, alumno, fecha_inicio, fecha_fin, anulado):
    return HttpResponse(simplejson.dumps(boleta_json), mimetype='application/json')

@login_required(login_url='/wvb/')
def search_boleta_json(request, serie, numero):
    cursor = connection.cursor()
    boleta = cursor.execute("SELECT * FROM boleta_alumno WHERE serie = '%s' AND numero = '%s'" % (serie, numero)).fetchone()
    boleta_json = {
				  "valido" : boleta[0],
				  "serie" : boleta[1],
				  "saldo" : str(boleta[2]),
				  "numero" : boleta[3],
				  "fecha" : str(boleta[4]),
				  "importe" : str(boleta[5]),
				  "concepto" : boleta[6],
				  "alumno" : u'%s, %s' % (boleta[7],boleta[8]),
				  "codigo" : boleta[9],
				  }
    return HttpResponse(simplejson.dumps(boleta_json), mimetype='application/json')

templates/boleta/boleta_historial.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Historial Boletas{% endblock %}
{% block csspage %}
	<style>
		#id_alumno{
			width: 97.8%;
		}
		table {
			font-size:11px;
		}
	</style>
{% endblock %}
{% block content %}
	<form method="post" action="#" class="yform full" role="application">
		{% csrf_token %}
		<fieldset>
			<legend>Pagos Realizados</legend>
			<div class="subcolumns">
				<div id="tabs">
					<ul>
						<li><a href="#tabs-1">Hoy</a></li>
						<li><a href="#tabs-2">Personalizado</a></li>
					</ul>
					<div id="tabs-1">
						<div class="subcolumns">
							<table id="tb_boletas">
								<thead>
									<tr>
										<th>Serie - Número</th>
										<th>Alumno</th>
										<th>Concepto</th>
										<th>Importe</th>
										<th>Válido</th>
										<th>&nbsp;</th>
									</tr>
								</thead>
								<tbody>
									{% for boleta in boletas %}
									<tr>
										<td>{{ boleta }}</td>
										<td>{{ boleta.alumno }}</td>
										<td>{{ boleta.concepto }}</td>
										<td>S/. {{ boleta.importe }}</td>
										<td><input type="checkbox" checked={{ boleta.valido }}/></td>
										<td></td>
									</tr>
									{% endfor %}
								</tbody>
								<tfoot>
									<tr>
										<th>Total</th>
										<th colspan="4"><label id="id_total"></label></th>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
					<div id="tabs-2">
						<fieldset>
							<legend>Opciones</legend>
							<div class="subcolumns">
								<div class="c50l">
									<div class="subcl type-text">
										<label for="id_boleta">Serie:</label>
										<input type="text" id="id_serie" name="serie"/>
									</div>
									<div class="subcl type-text">
										<label for="id_codigo_alumno">Alumno:</label>
										<input type="text" id="id_alumno" name="alumno"/>
									</div>
									<div class="subcl type-check">
										<label>Anulado:</label>
										<div>
											<label for="id_anulado">&nbsp;</label>
											<input type="checkbox" id="id_anulado" name="anulado"/>
										</div>
									</div>
								</div>
								<div class="c50r">
									<div class="subcl type-text">
										<label for="id_boleta">Número:</label>
										<input type="text" id="id_numero" name="numero"/>
									</div>
									<div class="subcl type-text">
										<label for="id_fecha_inicio">Fecha Inicio:</label>
										<input type="text" id="id_fecha_inicio" name="fecha_inicio"/>
									</div>
									<div class="subcl type-text">
										<label for="id_fecha_fin">Fecha Fin:</label>
										<input type="text" id="id_fecha_fin" name="fecha_fin"/>
									</div>
								</div>
							</div>
						</fieldset>
						<div class="type-button">
							<input type="button" value="Actualizar" class="button" id="hoy" name="hoy" onclick="getBoletasDate();"/>
							<input type="reset" value="Limpiar" class="reset" id="reset" name="reset"/>
						</div>
						<div class="subcolumns">
							<table id="tb_boletas_search">
								<thead>
									<tr>
										<th>Serie - Número</th>
										<th>Alumno</th>
										<th>Concepto</th>
										<th>Importe</th>
										<th>Válido</th>
										<th>&nbsp;</th>
									</tr>
								</thead>
								<tbody>
								</tbody>
								<tfoot>
									<tr>
										<th>Total</th>
										<th colspan="4"><label id="id_total_date"></label></th>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="type-button">
				<input type="button" value="Imprimir" class="button" id="imprimir" name="imprimir" />
			</div>
		</fieldset>
	</form>
{% endblock %}
{% block left-bar %}
    {% include "home/pago.html" %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL }}js/base.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/boleta.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/jquery.tablesorter.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/jquery.uitablefilter.js" type="text/javascript"></script>
	<script>
		var serie = null, numero = null, alumno = null, fecha_inicio = null,fecha_fin = null,anulado = null;
		var meses = new Array("Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic");
		var fecha_emision = new Date({{ boleta.fecha_emision__year }});
		var tb_boletas = null;
		var tb_boletas_search = null;
		var alumno_codigo;
		$(document).ready(function() {
			run();
			serie = $("#id_serie");
			numero = $("#id_numero");
			alumno = $( "#id_alumno" ).autocomplete({
						source: "/boleta/boleta-alumno-campus-id/json/",
						select: function( event, ui ) {
							alumno_codigo = ui.item.id;
						},
						minLength: 2,
					});
			anulado = $("#id_anulado");			
			tboletas = $("#tb_boletas");
			tb_boletas_search = $("#tb_boletas_search");
			$("#tabs").tabs();
			$("#tb_boletas").tablesorter();
			fecha_inicio = $("#id_fecha_inicio").datepicker({
				changeMonth: true,
				changeYear: true, 
				closeText: 'X',
				dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
				gotoCurrent: true,
				monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
				yearRange: '1988:'+fecha_emision.getFullYear(),
				dateFormat: 'mm/dd/yy',
				currentText: 'Now',
				onSelect: function(dateText, inst) {
					fecha_fin.datepicker("option", "minDate", fecha_inicio.datepicker("getDate"));
					}
				}
			);
			fecha_fin = $("#id_fecha_fin").datepicker({
				changeMonth: true,
				changeYear: true, 
				closeText: 'X',
				dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
				gotoCurrent: true,
				monthNamesShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
				yearRange: '1988:'+fecha_emision.getFullYear(),
				dateFormat: 'mm/dd/yy', 
				currentText: 'Now'}
				);
			sumarMontosHoy();
			$("#bt_imprimir").button({
				text:true,
				icons:{
					primary: "ui-icon-print"
				}
			}).click(function(){
				imprimir();
			});
			$("#id_contro_pago").val(meses[fecha_emision.getMonth()]+" "+fecha_emision.getYear().toString().substr(0,2))
		});
		function redirectAnular(){
			var str_options = null;
			str_options+=serie.val() === "" ? 'no/' : serie.val()+"/";
			str_options+=numero.val() === "" ? 'no/' : numero.val()+"/";
			str_options+=alumno.val() === "" ? 'no/' : alumno.val()+"/";
			str_options+=fecha_inicio.val() === "" ? 'no/' : fecha_inicio.val().replace(/[/]/g,"-")+"/";
			str_options+=fecha_fin.val() === "" ? 'no/' : fecha_fin.val().replace(/[/]/g,"-")+"/";
			str_options+=anulado.val() === "" ? 'no/' : anulado.val()+"/";
			$.getJSON("/boleta/buscar/"+srt_options+"json/",
        	 function(data){
	            $.each(data,function(key,value){
					
        	    });
        	    tboletas.tablesorter();
        	    sumarMontosHoy();
			 });
		}
	</script>
        <script type="text/javascript">
        	var talumnos = null;
        	var divcont=null;
        	var saldo=null;
        	var fecha_emision=new Date();
			function getBoletas(){
        	 $.getJSON("/wvb/json/boletas/nodate-nodate-"+1+"-"+tboletas.find("tbody tr").length,
        	 function(data){
	            $.each(data,function(key,value){
					if(value.serienumero != "0"){
						var tr = $("<tr></tr>")
						var chk = $("<input type='checkbox'/>")
						tr.append("<td>"+value.serienumero+"</td>");
						tr.append("<td>"+value.alumno+"</td>");
						tr.append("<td>"+value.concepto+"</td>");
						tr.append("<td>S/. "+value.monto+"</td>");
						if(value.valido)
							chk.attr("checked","checked");
						tr.append($("<td></td>").append(chk));
						tr.prependTo("#tb_boletas > tbody");
        	        }
        	    });
        	    tboletas.tablesorter();
        	    sumarMontosHoy();
			 });
        	}
        	function getBoletasDate(){
        	 var fecha_inicio=$("#id_fecha_inicio").val().replace(/[/]/g,"");
        	 var fecha_fin=$("#id_fecha_fin").val().replace(/[/]/g,""); 	 
        	 if(fecha_inicio!="" && fecha_fin!=""){
        	 $.getJSON("/wvb/json/boletas/"+fecha_inicio+"-"+fecha_fin+"-"+0+"-"+tboletas.find("tbody tr").length,
        	 function(data){
				 tboletasdate.find("tbody tr:not(:first)").remove();
	            $.each(data,function(key,value){
					if(value.serienumero != "0"){
						var tr = $("<tr></tr>")
						var chk = $("<input type='checkbox'/>")
						tr.append("<td>"+value.serienumero+"</td>");
						tr.append("<td>"+value.alumno+"</td>");
						tr.append("<td>"+value.concepto+"</td>");
						tr.append("<td>S/. "+value.monto+"</td>");
						if(value.valido)
							chk.attr("checked","checked");
						tr.append($("<td></td>").append(chk));
						tboletasdate.append(tr);
        	        }
        	    });
        	    tboletasdate.tablesorter();
        	    sumarMontosDate();
			 });
			 }
        	}
        	function sumarMontosHoy(){
				var total = 0;
				$.each(tboletas.find("tbody tr"), function(){
					if(this.cells[4].childNodes.item(0).checked){
						total+=parseFloat(this.cells[3].childNodes.item(0).data.toString().replace("S/. ",""));
					}
				});
				$("#id_total").html("S/. "+total)
			}
			function sumarMontosDate(){
				var total = 0;
				$.each(tboletasdate.find("tbody tr"), function(){
					if(this.cells[4].childNodes.item(0).checked){
						total+=parseFloat(this.cells[3].childNodes.item(0).data.toString().replace("S/. ",""));
					}
				});
				$("#id_total_date").html("S/. "+total)
			}
        	//setInterval(getBoletas,60000);
        </script>

{% endblock %}

templates/boleta/boleta_imprimir.html
{% extends 'base.html' %}
{% block title %}W.V.B. - Imprimir{% endblock %}
{% block csspage %}
	<style>
		#id_alumno{
			width: 97.8%;
		}
	</style>
{% endblock %}
{% block content %}
	<form method="post" action="#" class="yform full" role="application">
		{% csrf_token %}
		<fieldset>
			<legend>Pensión</legend>
			<div id="imprimir" class="subcolumns">
				<div class="c50l">
					<div class="subcl type-text">
						{{ codigo.errors }}
						<label for="id_codigo_alumno">Codigo Alumno:</label>
						<input type="text" id="id_codigo_alumno" name="codigo_alumno" value="{{ boleta.alumno.alumno.codigo }}" maxlength="6" readonly="readonly"/>
					</div>
				</div>
				<div class="c50r">
					<div class="subcl type-text">
						{{ serie.errors }}
						<label for="id_boleta">Boleta:</label>
						<input type="text" id="id_boleta" name="codigo_boleta" value="{{ boleta.serie }}-{{ boleta.numero }}" readonly="readonly"/>
					</div>
				</div>
				<div class="subcolumns">
					<div class="subcl type-text">
						{{ alumno.errors }}
						<label for="id_alumno">Alumno:</label>
						<input type="text" id="id_alumno" name="alumno" value="{{ boleta.alumno.alumno.get_full_name }}" readonly="readonly"/>
					</div>
					<div class="c50l">
						<div class="subcl type-text">
							<label for="id_concepto">Concepto:</label>
							<input type="text" name="concepto" id="id_concepto" value="{{ boleta.concepto }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_fecha_emision">Fecha Emisión:</label>
							<input type="text" name="fecha_emision" id="id_fecha_emision" value="{{ boleta.fecha_emision }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_importe">Importe:</label>
							<input type="text" name="importe" id="id_importe" value="{{ boleta.importe }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_saldo">Saldo:</label>
							<input type="text" name="saldo" id="id_saldo" value="{{ boleta.saldo }}" readonly="readonly"/>
						</div>
					</div>
					<div class="c50r">
						<div class="subcl type-text">
							<label for="id_carrera">Carrera:</label>
							<input type="text" name="carrera" id="id_carrera" value="{{ boleta.alumno.campus.ciclo.carrera }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_saldo">Ciclo - Seccion:</label>
							<input type="text" name="ciclo_seccion" id="id_ciclo_seccion" value="{{ boleta.alumno.campus.ciclo.ciclo }} - {{ boleta.alumno.campus.get_seccion }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_saldo">Turno:</label>
							<input type="text" name="turno" id="id_turno" value="{{ boleta.alumno.campus.get_turno }}" readonly="readonly"/>
						</div>
						<div class="subcl type-text">
							<label for="id_contro_pago">Control Pago:</label>
							<input type="text" name="contro_pago" id="id_contro_pago" readonly="readonly"/>
						</div>
					</div>
				</div>
			</div>
		</fieldset>
		<div class="type-button">
			<input type="botton" value="Imprimir" class="botton" id="bt_imprimir" name="imprimir" />
		</div>
	</form>
{% endblock %}
{% block left-bar %}
    {% include "home/pago.html" %}
{% endblock %}
{% block scriptjs %}
	<script src="{{ STATIC_URL  }}js/base.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/boleta.js" type="text/javascript"></script>
	<script>
		var meses = new Array("Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic");
		var fecha_emision = new Date({{ boleta.fecha_emision__year }});
		$(document).ready(function() {
			run();
			$("#bt_imprimir").button({
				text:true,
				icons:{
					primary: "ui-icon-print"
				}
			}).click(function(){
				imprimir();
			});
			$("#id_contro_pago").val(meses[fecha_emision.getMonth()]+" "+fecha_emision.getYear().toString().substr(0,2))
		});
		function 
	</script>
{% endblock %}